### PR TITLE
`CoupledSDEs` pretty printing

### PR DESCRIPTION
**Pull request by reykboerner**
See #97

### CODE REVIEW

**Comment by reykboerner** [comment]
@oameye do you have an idea why the `additional_details(::CoupledSDEs)` function in `src/CoupledSDEs.jl` does not take effect? And why `CoupledSDEs.integ.f` returns `SDEFunction` instead of the deterministic function `f`?

I can look further into it later but maybe you know the answer immediately.

**Comment by oameye** [comment]
not sure how pretty printing work in julia. Don't you need to define `show` methods?

Re the `SDEFunction`: We remake the `SDEProblem` to multiple `g` with the `noise_strength`. Because SDEProblem has multiple methods (e.g., `SDEProblem(f::SDEFunction, ...)` and `SDEProblem(f::Function, g::Function)`), remaking `g` in SDEProblem was nontrivial. See https://github.com/SciML/SciMLBase.jl/issues/735 for details.
https://github.com/JuliaDynamics/CriticalTransitions.jl/blob/754a850ebea2996bec7d0977df497c25b7d49a3e/src/CoupledSDEs.jl#L124-L125

**Comment by oameye** [comment]
@reykboerner Can you give you opinion about the pretty printing?

**Comment by oameye** [comment]
pretty printing is moved into DSB.jl. See https://github.com/JuliaDynamics/DynamicalSystemsBase.jl/pull/212

**Pull request closed without merging**
